config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  root 'static_pages#home'
  get "/home", to: "static_pages#home"
  get '/signup', to: "users#new"
  post "/signup", to: "users#create"
  # get "/post", to: "posts#new"
  # post "/post", to: "posts#create"
  # get "/all_posts", to: "posts#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      # redirect_to all_posts_url
      redirect_to @post
    else
      render "new"
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to
    else
      render "new"
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

  <div class="container">
    <%= link_to "Blog", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_url %></li>

        <li><%= link_to "Help", "#" %></li>

        <li><%= link_to "Post", new_post_path %></li>

      </ul>
    </nav>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/posts/index.html.erb
<h1>All posts</h1>

<% @posts.each do |p| %>
  <li>
    <%= link_to p.content, p %>
  </li>
<% end %>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <br>
  <br>
  <br>
  <br>
    <%= form_for(@post) do |f| %>


      <%= f.label :content %>
      <%= f.text_field :content %>

      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<br>
<br>
<br>
<br>
<h1><%= @post.content %></h1>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Blog</h1>



  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>


      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :email %>
      <%= f.email_field :email %>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <br>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<br>
<br>
<br>
<br>
<h1><%=@user.name%></h1>